frontend/src/fixtures/bookFixtures.js
In this PR, we add fixtures for book objects to be used in testing and storybook entries.
=> Add bookFixtures.js

frontend/src/fixtures/iceCreamShopFixtures.js
In this PR, we add fixtures for ice cream shop objects to be used in testing and storybook entries.
=> Add fixtures for ice cream shops

frontend/src/fixtures/amusementParksFixtures.js
In this PR, we add the fixtures for Amusement Parks
=> Add Amusement Park Fixtures

frontend/src/main/utils/iceCreamShopUtils.js, frontend/src/tests/utils/iceCreamShopUtils.test.js
In this commit, I added iceCreamShopUtils.js and iceCreamShopUtils.test.js.
=> Add iceCreamShopUtils.js and tests

frontend/src/main/utils/bookUtils.js, frontend/src/tests/utils/bookUtils.test.js
Add the bookUtils.js and the bookUtils.text.js
=> added bookUtils and testing part

frontend/src/main/components/Books/BookTable.js, frontend/src/stories/components/Books/BookTable.stories.js, frontend/src/tests/components/Books/BookTable.test.js
In this PR, we add BookTable.js, as well as its associated .test and .stories files.
=> Add BookTable component

frontend/src/main/components/AmusementParks/amusementParksForm.js, frontend/src/stories/components/AmusementParks/amusementParksForm.stories.js, frontend/src/tests/components/AmusementParks/amusementParksForm.test.js
In this PR, the AmusementParksForm and corresponding tests are addded
=> Added Amusement Parks Form 

frontend/src/main/components/Books/BookForm.js, frontend/src/stories/components/Books/BookForm.stories.js, frontend/src/tests/components/Books/BookForm.test.js
In this PR, I adding the bookform component with related storybook and tests.
=> adding the BookForm

frontend/src/main/components/IceCreamShops/IceCreamShopForm.js, frontend/src/stories/components/IceCreamShops/IceCreamShopForm.stories.js, frontend/src/tests/components/IceCreamShops/IceCreamShopForm.test.js
Added IceCreamShopForm.js, as well as the storybook and tests for it.
=> Add IceCreamShopForm

frontend/src/main/components/IceCreamShops/IceCreamShopTable.js, frontend/src/stories/components/IceCreamShops/IceCreamShopTable.stories.js, frontend/src/tests/components/IceCreamShops/IceCreamShopTable.test.js
=> Add Ice Cream Shop Table

frontend/src/main/pages/Books/BookDetailsPage.js, frontend/src/tests/pages/Books/BookDetailsPage.test.js
In this PR, we add BookDetailsPage and its test, according to the template provided in the restaurant version.
=> Add BookDetailsPage

frontend/src/main/pages/Books/BookCreatePage.js, frontend/src/tests/pages/Books/BookCreatePage.test.js
In this PR , I add the BookCreatePage component.
=>  Adding BookCreatePage

frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/IceCreamShops/IceCreamShopIndexPage.js, frontend/src/tests/pages/IceCreamShops/IceCreamShopIndexPage.test.js
=> Add Ice Cream Shop Index Page

frontend/src/main/pages/IceCreamShops/IceCreamShopCreatePage.js, frontend/src/tests/pages/IceCreamShops/IceCreamShopCreatePage.test.js
Added IceCreamShopCreatePage and its tests
=> Added IceCreamShopCreatePage

frontend/src/main/pages/AmusementParks/AmusementParkCreatePage.js, frontend/src/tests/pages/AmusementParks/AmusementParksCreatePage.test.js
In this PR, I added the create pages and run through all corresponding tests
=> Added the Create Page and corresponding tests

frontend/src/main/pages/IceCreamShops/IceCreamShopCreatePage.js, frontend/src/main/pages/IceCreamShops/IceCreamShopEditPage.js, frontend/src/tests/pages/IceCreamShops/IceCreamShopCreatePage.test.js, frontend/src/tests/pages/IceCreamShops/IceCreamShopEditPage.test.js
Added IceCreamShopEditPage.js and its tests.
=> Add IceCreamShopEditPage

frontend/src/main/pages/Books/BookEditPage.js, frontend/src/tests/pages/Books/BookEditPage.test.js
In this PR, I add the edit page component and the relative tests.
=> adding edit page and tests

frontend/src/main/pages/AmusementParks/AmusementParkEditPage.js, frontend/src/tests/pages/AmusementParks/AmusementParksEditPage.test.js
In this PR, I add the AmusementParkEditPage and passed all corresponding tests
=> Add the AmusementPark Edit Page and corresponding tests

frontend/src/main/pages/IceCreamShops/IceCreamShopDetailsPage.js, frontend/src/tests/pages/IceCreamShops/IceCreamShopDetailsPage.test.js
=> Add Ice Cream Shop Details Page

frontend/src/main/components/Books/BookTable.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/Books/BookIndexPage.js, frontend/src/tests/components/Books/BookTable.test.js, frontend/src/tests/pages/Books/BookDetailsPage.test.js, frontend/src/tests/pages/Books/BookIndexPage.test.js
In this PR, we add BookIndexPage.js and its test file according to the example in the restaurant version.
Edit: BookTable previously did not display the "Author" field, and so tests for pages containing the component (namely BookIndexPage and BookDetailsPage) did not look for it. This PR also updates BookTable to display the "Author" field and updates those other pages' tests to test for its existence.
=> Create BookIndexPage and fix missing "Author" field in various files

frontend/src/App.js
In this PR, I add the link and routes for book button in the navigation bar.
=> hx - add related links and route for book

frontend/src/main/components/AmusementParks/AmusementParksTable.js, frontend/src/stories/components/AmusementParks/AmusementParksTable.stories.js, frontend/src/tests/components/AmusementParks/AmusementParksTable.test.js
In this PR, we add the table for Amusement Parks as well as stories and tests for it.
=> Add Amusement Parks Table

frontend/src/App.js, frontend/src/main/components/IceCreamShops/IceCreamShopTable.js, frontend/src/main/pages/IceCreamShops/IceCreamShopCreatePage.js, frontend/src/main/pages/IceCreamShops/IceCreamShopDetailsPage.js, frontend/src/main/pages/IceCreamShops/IceCreamShopEditPage.js, frontend/src/main/pages/IceCreamShops/IceCreamShopIndexPage.js, frontend/src/tests/components/IceCreamShops/IceCreamShopTable.test.js, frontend/src/tests/pages/IceCreamShops/IceCreamShopIndexPage.test.js
In the first commit, I added links for IceCreamShop in App.js and fixed an error in IceCreamShopTable.js. IceCreamShop now has a working table and working navbar link.
In the second commit, I fixed some formatting "issues" regarding the text on the pages for IceCreamShops (IceCreamShops -> Ice Cream Shops).
In the third, I realized that in changing the formatting of the "Create Ice Cream Shop" button, I had to change the test for it too, as it was still looking for the button "Create IceCreamShops".
=> Fixed IceCreamShops links

frontend/src/App.js, frontend/src/fixtures/iceCreamShopFixtures.js, frontend/src/main/components/IceCreamShops/IceCreamShopTable.js, frontend/src/main/pages/IceCreamShops/IceCreamShopCreatePage.js, frontend/src/main/pages/IceCreamShops/IceCreamShopDetailsPage.js, frontend/src/main/pages/IceCreamShops/IceCreamShopEditPage.js, frontend/src/main/pages/IceCreamShops/IceCreamShopIndexPage.js, frontend/src/tests/components/IceCreamShops/IceCreamShopTable.test.js, frontend/src/tests/pages/IceCreamShops/IceCreamShopIndexPage.test.js
In addition to PR [57](https://github.com/ucsb-cs156-s23/team01-s23-7pm-3/pull/57), I also changed the format of fixtures to be more consistent with tests.
=> IceCreamShop misc fixes

frontend/src/tests/pages/IceCreamShops/IceCreamShopDetailsPage.test.js
In this PR, I make a two-line change to add the flavor field to IceCreamShopDetailsPage's test file.
=> Fix IceCreamShopDetailsPage.test to include the flavor field

frontend/src/main/pages/AmusementParks/AmusementParksDetailsPage.js, frontend/src/tests/pages/AmusementParks/AmusementParksDetailsPage.test.js
In this PR, we fixed an error where the details page for amusement parks wasn't functional
=> Fixed errors on amusement park details page and tests
